# Generated by Django 4.1 on 2023-01-24 11:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тегі')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('subject', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тақырыбы')),
                ('message', models.TextField(verbose_name='Хабарлама')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Уақыты')),
            ],
            options={
                'verbose_name': 'Сұрақ',
                'verbose_name_plural': 'Сұрақтар',
            },
        ),
        migrations.CreateModel(
            name='Dogovor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Келісім-шарт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сипаттама')),
                ('organization', models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мекеме')),
            ],
            options={
                'verbose_name': 'Келісім-шарт',
                'verbose_name_plural': 'Келісім-шарттар',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Аты-жөні')),
                ('message', models.TextField(verbose_name='Пікір')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='Сурет')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Уақыты')),
            ],
            options={
                'verbose_name': 'Пікір',
                'verbose_name_plural': 'Пікірлер',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Жоба аты')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сипаттама')),
                ('organization', models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мекеме')),
            ],
            options={
                'verbose_name': 'Жоба',
                'verbose_name_plural': 'Жобалар',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тауар аты')),
                ('price', models.IntegerField(verbose_name='Бағасы')),
                ('count', models.IntegerField(verbose_name='Саны')),
                ('organization', models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мекеме')),
            ],
            options={
                'verbose_name': 'Тауар',
                'verbose_name_plural': 'Тауарлар',
            },
        ),
        migrations.CreateModel(
            name='Platej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('ndc', models.IntegerField(verbose_name='НДС')),
                ('dogovor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.dogovor', verbose_name='Келісім-шарт')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мекеме')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.project', verbose_name='Жоба')),
            ],
            options={
                'verbose_name': 'Төлем',
                'verbose_name_plural': 'Төлемдер',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Уақыты')),
                ('dogovor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.dogovor', verbose_name='Келісім-шарт')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мекеме')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.project', verbose_name='Жоба')),
            ],
            options={
                'verbose_name': 'Тапсырыс',
                'verbose_name_plural': 'Тапсырыстар',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тақырыбы')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('organization', models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мекеме')),
            ],
            options={
                'verbose_name': 'Ескертпе',
                'verbose_name_plural': 'Ескертпелер',
            },
        ),
    ]
