# Generated by Django 4.1 on 2023-01-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_dogovor_organization_alter_notes_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platej',
            options={'verbose_name': 'Сатылым', 'verbose_name_plural': 'Сатылымдар'},
        ),
        migrations.AlterField(
            model_name='platej',
            name='ndc',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='НДС'),
        ),
        migrations.AlterField(
            model_name='platej',
            name='sum',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Сумма'),
        ),
    ]
