# Generated by Django 4.1 on 2023-02-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_platej_ndc_alter_platej_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=150, verbose_name='Мекен-жай'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='oplata',
            field=models.CharField(choices=[('Карта', 'Карта'), ('Қолма-қол', 'Қолма-қол'), ('QR-код', 'QR-код')], default=1, max_length=150, verbose_name='Төлем түрі'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Төленді/Төленбеді'),
        ),
    ]
