# Generated by Django 4.1 on 2023-02-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_remove_platej_place_product_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platej',
            name='ndc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='НДС'),
        ),
    ]
