# Generated by Django 4.1 on 2023-03-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_platej_ndc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(max_length=150, verbose_name='Тегі')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьер',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='dogovor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='project',
        ),
        migrations.AddField(
            model_name='order',
            name='platej',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.platej', verbose_name='Сатылым'),
        ),
        migrations.AddField(
            model_name='platej',
            name='count',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Саны'),
        ),
        migrations.AlterField(
            model_name='platej',
            name='status',
            field=models.CharField(choices=[('Төленді', 'Төленді'), ('Төленбеді', 'Төленбеді')], max_length=150, verbose_name='Төленді/Төленбеді'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.courier', verbose_name='Жоба'),
        ),
    ]
