# Generated by Django 4.1 on 2023-03-16 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0010_courier_remove_order_dogovor_remove_order_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мекеме'),
            preserve_default=False,
        ),
    ]
